### PR TITLE
Added hover effect to #speed-menu's options

### PR DESCRIPTION
**Pull request by danimesq**

### CODE REVIEW

**Comment by nt1m** [comment]
The hover state should be lighter than the selected state.

**Comment by danimesq** [comment]
Or we can swap the design of the two. The hover gray, and the selected white.

**Comment by nt1m** [comment]
I wanted to go with a blue selected state and a white hover state, but the selected state seems forced by the browser styles (especially firefox).

**Comment by danimesq** [comment]
What do you suggest that we can do?

**Comment by danimesq** [comment]
@nt1m

**Comment by nt1m** [comment]
@Plasmmer See my first comment, the hover state should be less visible than the selected state (it's not the case in the screenshot).

A text-shadow is a good option.

**Comment by danimesq** [comment]
Done.

**Pull request merged**
