### PR TITLE
Added border to sidebar

### PR DESCRIPTION
**Pull request by danimesq**

### CODE REVIEW

**Comment by nt1m** [comment]
I think it's better without one, sorry.

**Comment by danimesq** [comment]
Ok, I understand your point. But in design, 1px at minum border is needed in this sidebar. Please reconsidere with care.

**Comment by danimesq** [comment]
In modern design concepts, elements need sobreposition, like in this concept for sidebar/navbar: http://i.imgur.com/9Ry2W9v.png

**Comment by danimesq** [comment]
If you reconsider decision, you can reopen this PR and I'll make other commit with unique+discret sobreposition for sidebar with 2px border.

**Pull request closed without merging**
